// cards.js
const ORIGINAL_CARDS = [
// Unit 1 — Structure, Bonding and Introduction to Organic Chemistry
{cat:"unit1",q:"Moles from mass",a:"n = mass (g) ÷ Mr; use Avogadro constant L = 6.02 × 10²³ mol⁻¹ to convert moles ↔ particles",detail:"Always convert mass to grams and use consistent Mr for the species in the equation"},
{cat:"unit1",q:"Empirical vs molecular formula",a:"Empirical = simplest whole-number ratio of atoms; molecular = actual number of atoms per molecule",detail:"Molecular formula = (empirical formula)ₙ; find n from Mr ÷ empirical formula mass"},
{cat:"unit1",q:"Percentage yield",a:"% yield = (actual mass ÷ theoretical mass) × 100",detail:"Theoretical mass from balanced equation and limiting reagent; losses reduce yield below 100%"},
{cat:"unit1",q:"Percentage atom economy",a:"% atom economy = (Mr of desired product ÷ ΣMr of all products) × 100",detail:"Higher atom economy = less waste atoms; addition reactions often have 100% atom economy"},
{cat:"unit1",q:"Subatomic particles — mass and charge",a:"Proton: +1, ~1 u; neutron: 0, ~1 u; electron: –1, ~1/1840 u",detail:"Mass number A = protons + neutrons; atomic number Z = protons only"},
{cat:"unit1",q:"Isotopes",a:"Same atomic number (same element), different mass number due to different neutron count",detail:"Relative atomic mass is weighted average of isotope masses"},
{cat:"unit1",q:"Electronic configuration notation",a:"Fill subshells in order: 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ …; max 2 electrons per orbital",detail:"Use s, p, d subshells; e.g. Fe atom: [Ar] 3d⁶ 4s² (4s fills before 3d completes for atoms)"},
{cat:"unit1",q:"First ionisation energy — trends",a:"Increases across a period (nuclear charge ↑, shielding similar); decreases down a group (outer electron further from nucleus)",detail:"Exceptions at Group 2→3 and 5→6 due to subshell stability and repulsion"},
{cat:"unit1",q:"Successive ionisation energies",a:"Large jump when removing an electron from a new inner shell — evidence for electron shells",detail:"Plot log(IE) vs electron removed; jumps show shell structure"},
{cat:"unit1",q:"Bonding types and structure",a:"Ionic: metal + non-metal, giant lattice; covalent: shared electrons; metallic: delocalised electrons in lattice",detail:"Bond type relates to melting point, conductivity, solubility"},
{cat:"unit1",q:"VSEPR shapes and bond angles",a:"2 e⁻ pairs: linear 180°; 3: trigonal planar 120°; 4: tetrahedral 109.5°; 3 bonds + 1 lone pair: pyramidal ~107°; 2 bonds + 2 LP: bent ~104.5°",detail:"Count bonding pairs + lone pairs on central atom; lone pairs repel more than bonding pairs"},
{cat:"unit1",q:"Structure types and properties",a:"Giant ionic/covalent: high mp, brittle; simple molecular: low mp, weak IMFs; metallic: malleable, conducts",detail:"Covalent network (diamond, SiO₂) vs simple molecules (I₂, H₂O)"},
{cat:"unit1",q:"Intermolecular forces",a:"van der Waals (all molecules); permanent dipole–dipole; hydrogen bonding (N–H, O–H, F–H)",detail:"H-bonding strongest IMF; explains anomalous boiling points of H₂O, NH₃, HF"},
{cat:"unit1",q:"Homologous series and functional groups",a:"Same functional group, similar reactions, gradation in physical properties; general formula e.g. alkanes CₙH₂ₙ₊₂",detail:"IUPAC: longest chain, lowest locants, correct suffix (-ane, -ene, -ol)"},
{cat:"unit1",q:"Structural isomerism",a:"Chain (different carbon skeleton), positional (functional group position), functional group (different FG)",detail:"Same molecular formula, different structural formula"},
{cat:"unit1",q:"Alkane combustion",a:"Complete: alkane + O₂ → CO₂ + H₂O; incomplete: CO and/or C (soot) also formed",detail:"Excess O₂ favours complete combustion"},
{cat:"unit1",q:"Free radical substitution of alkanes",a:"Cl₂ or Br₂, UV light; initiation (homolytic fission), propagation (radical chain), termination (radicals combine)",detail:"Mixture of products possible; controlled conditions favour one halogenoalkane"},
{cat:"unit1",q:"Alkene + H₂",a:"H₂, Ni/Pt catalyst, ~150°C → alkane",detail:"Catalytic hydrogenation; addition across C=C"},
{cat:"unit1",q:"Alkene + HBr — Markovnikov",a:"H adds to C with more H already; Br to more substituted C (Markovnikov's rule)",detail:"Electrophilic addition; carbocation intermediate stability explains regioselectivity"},
{cat:"unit1",q:"Alkene + Br₂",a:"Br₂, room temperature → dibromoalkane; bromine water decolourises (test for C=C)",detail:"Electrophilic addition; no catalyst needed"},
{cat:"unit1",q:"Alkene hydration",a:"H₂O(g), conc. H₃PO₄, ~300°C, high pressure → alcohol",detail:"Industrial route to ethanol; electrophilic addition"},
{cat:"unit1",q:"Addition polymerisation",a:"Alkene monomers → poly(alkene); high pressure + Ziegler–Natta or radical initiator",detail:"Repeating unit shows original C=C opened to –C–C– backbone"},
{cat:"unit1",q:"Cold dilute KMnO₄ on alkene",a:"Syn dihydroxylation → diol (–CH(OH)–CH(OH)–)",detail:"Purple MnO₄⁻ decolourises; distinguishes alkene from alkane"},
{cat:"unit1",q:"Hot concentrated KMnO₄ on alkene",a:"Oxidative cleavage of C=C — carbonyl compounds or CO₂ depending on substitution",detail:"Different outcome from cold dilute conditions — always state conditions in exams"},

// Unit 2 — Energetics, Group Chemistry, Halogenoalkanes and Alcohols
{cat:"unit2",q:"Standard enthalpy of formation (ΔfH°)",a:"Enthalpy change when 1 mol of compound forms from elements in standard states",detail:"ΔH°f of element in standard state = 0 kJ mol⁻¹"},
{cat:"unit2",q:"Standard enthalpy of combustion (ΔcH°)",a:"Enthalpy change when 1 mol of substance burns completely in O₂ under standard conditions",detail:"Always exothermic (negative ΔH) for organic fuels"},
{cat:"unit2",q:"Hess's law",a:"Total enthalpy change is independent of route; ΔH for cycle sums to zero",detail:"Use formation, combustion or bond enthalpy cycles to find unknown ΔH"},
{cat:"unit2",q:"Bond enthalpy calculations",a:"ΔH ≈ Σ(bonds broken) – Σ(bonds formed); breaking endothermic (+), forming exothermic (–)",detail:"Mean bond enthalpies are averages — approximate only"},
{cat:"unit2",q:"Calorimetry",a:"q = mcΔT; then ΔH = –q ÷ moles (watch sign and units)",detail:"Heat loss to surroundings, incomplete combustion, evaporation are common errors"},
{cat:"unit2",q:"Hydrogen bonding — requirements",a:"H bonded directly to N, O or F; lone pair on neighbouring N/O/F",detail:"Raises bp and water solubility for molecules with –OH, –NH₂, etc."},
{cat:"unit2",q:"Oxidation and reduction (electrons)",a:"Oxidation: loss of electrons; reduction: gain of electrons; use oxidation numbers to track",detail:"OIL RIG — Oxidation Is Loss, Reduction Is Gain"},
{cat:"unit2",q:"Group 1 reactivity trend",a:"Reactivity increases down group: Li < Na < K with water (faster H₂, more vigorous)",detail:"Also react with O₂ and Cl₂; lower IE makes oxidation easier"},
{cat:"unit2",q:"Group 2 — reactions and uses",a:"Ca with water → Ca(OH)₂; CaO (lime) neutralises acid; CaCO₃ limestone; BaSO₄ for barium meals (insoluble)",detail:"Mg reacts slowly with cold water, faster when heated"},
{cat:"unit2",q:"Group 7 — displacement and disproportionation",a:"More reactive halogen displaces less reactive halide; Cl₂ + cold NaOH → Cl⁻ + ClO⁻ + H₂O",detail:"Hot NaOH gives Cl⁻, ClO₃⁻, H₂O (disproportionation)"},
{cat:"unit2",q:"Halide ion test (AgNO₃)",a:"AgCl white, AgBr cream, AgI yellow precipitates; add dil. NH₃ — AgCl dissolves, AgBr partial, AgI insoluble",detail:"Acidify first to remove interfering ions"},
{cat:"unit2",q:"Collision theory",a:"Rate ∝ frequency of successful collisions with energy ≥ Ea; Maxwell–Boltzmann distribution shows fraction with E ≥ Ea",detail:"Only collisions with correct orientation and sufficient energy count"},
{cat:"unit2",q:"Factors affecting rate",a:"↑T: more particles with E ≥ Ea; ↑conc/pressure: more collisions; catalyst: lowers Ea",detail:"Catalyst does not shift equilibrium position"},
{cat:"unit2",q:"Dynamic equilibrium and Le Chatelier",a:"Forward and reverse rates equal; closed system; changing T, P, or concentration shifts position to oppose change",detail:"Catalyst speeds both directions equally — no shift"},
{cat:"unit2",q:"Halogenoalkane → alcohol",a:"Aqueous KOH, heat under reflux — nucleophilic substitution (SN)",detail:"OH⁻ is nucleophile; C–X bond breaks"},
{cat:"unit2",q:"Halogenoalkane → nitrile",a:"KCN in ethanol, reflux — extends carbon chain by 1",detail:"CN⁻ is nucleophile; product R–CN"},
{cat:"unit2",q:"Halogenoalkane → amine",a:"Excess NH₃ in ethanol, sealed tube, heat — primary amine",detail:"Excess NH₃ prevents polyalkylation"},
{cat:"unit2",q:"Halogenoalkane → alkene (elimination)",a:"Alcoholic KOH, heat — E2 elimination",detail:"OH⁻ acts as base; removes β-H; contrast with aqueous KOH → substitution"},
{cat:"unit2",q:"C–X bond and halogenoalkane reactivity",a:"Bond enthalpy C–F > C–Cl > C–Br > C–I; iodoalkanes react fastest in SN (weaker bond, better leaving group)",detail:"Rate also depends on SN1 vs SN2 and 1°/2°/3° structure"},
{cat:"unit2",q:"Alcohol classification and oxidation",a:"1° → aldehyde (distil) or acid (reflux); 2° → ketone; 3° — no reaction with K₂Cr₂O₇/H₂SO₄",detail:"Orange Cr₂O₇²⁻ → green Cr³⁺ on oxidation"},
{cat:"unit2",q:"Alcohol dehydration",a:"Conc. H₂SO₄ or H₃PO₄, ~170°C → alkene",detail:"Elimination mechanism; remove H and OH from adjacent carbons"},
{cat:"unit2",q:"Esterification",a:"Alcohol + carboxylic acid, conc. H₂SO₄ catalyst, heat — ester + water (reversible)",detail:"Fischer esterification; use excess reagent or remove water to improve yield"},
{cat:"unit2",q:"Mass spectrometry basics",a:"M⁺ peak gives molecular ion mass (Mr); fragmentation gives structural clues",detail:"High-resolution MS gives exact Mr for molecular formula"},
{cat:"unit2",q:"Key IR absorptions",a:"O–H broad ~3200–3550; C=O ~1680–1750; N–H ~3300–3500 cm⁻¹",detail:"Fingerprint region 1500–500 cm⁻¹ for detailed matching"},

// Unit 3 — Practical Skills in Chemistry I
{cat:"unit3",q:"Core Practical 1 — molar volume of gas",a:"Collect gas over water; use pV = nRT with corrected pressure (subtract water vapour)",detail:"Room T and pressure; moles from mass loss or volume measured"},
{cat:"unit3",q:"Core Practical 2 — enthalpy by calorimetry",a:"Measure ΔT for known mass of solution; q = mcΔT; scale to per mole of limiting reagent",detail:"Use polystyrene cup or lagged calorimeter; record initial and max T"},
{cat:"unit3",q:"Core Practical 3 — rate experiments",a:"Monitor rate by mass loss, gas volume, colour change, or titration of remaining reactant",detail:"Same temperature, surface area, and stirring for fair comparison"},
{cat:"unit3",q:"Core Practical 4 — enthalpy of combustion",a:"Spirit lamp heats water in calorimeter; ΔH from q = mcΔT and moles fuel burned",detail:"Heat loss to air and calorimeter lowers experimental |ΔH|"},
{cat:"unit3",q:"Core Practical 5 — halide tests",a:"Acidify sample, add AgNO₃(aq); observe ppt colour and behaviour with dil. NH₃",detail:"Nitric acid removes carbonate interference"},
{cat:"unit3",q:"Core Practical 6 — haloalkane preparation",a:"Heat reactants under reflux; purify by distillation; wash with separating funnel (neutralise acids, dry organic layer)",detail:"Anti-bumping granules; water condenser for reflux"},
{cat:"unit3",q:"Core Practical 7 — organic functional group tests",a:"Bromine water (alkene), Fehling's/Tollens' (aldehyde), K₂Cr₂O₇ (oxidisable groups), PCl₅ (–OH)",detail:"Record observations clearly: colour change, ppt, gas evolution"},
{cat:"unit3",q:"Core Practical 8 — chromatography",a:"Rf = distance moved by spot ÷ distance moved by solvent front (0–1)",detail:"Same solvent and temperature; mark solvent front before it dries past paper"},
{cat:"unit3",q:"Reflux vs distillation",a:"Reflux: vertical condenser, keeps volatile reactant in flask while heating; distillation: collect fraction boiling at target range",detail:"Reflux for slow reactions; distil to purify or separate by bp"},
{cat:"unit3",q:"Titration — good technique",a:"Rinse burette with solution; read meniscus at eye level; concordant titres within 0.10 cm³",detail:"c = n/V; V in dm³ for concentration in mol dm⁻³"},
{cat:"unit3",q:"Percentage error",a:"% error = (uncertainty ÷ measured value) × 100; combine % errors for multi-step calculations",detail:"Smallest division on instrument ÷ 2 often taken as absolute uncertainty"},
{cat:"unit3",q:"Random vs systematic error",a:"Random: scatter, reduced by repeats/averaging; systematic: consistent bias, reduced by calibration/blank",detail:"Systematic errors affect accuracy; random affect precision"},
{cat:"unit3",q:"Significant figures in practical work",a:"Report data to same precision as apparatus; calculated answer to lowest s.f. in calculation step",detail:"Trailing zeros after decimal are significant"},
{cat:"unit3",q:"COSHH and risk assessment",a:"Identify hazards (flammable solvents, corrosive acids); control exposure; ventilation, gloves, goggles",detail:"Never mouth-pipette; dispose of organic waste in labelled containers"},
{cat:"unit3",q:"Measuring gas volume — syringe or burette",a:"Gas syringe or inverted measuring cylinder over water; temperature and pressure noted",detail:"Saturated vapour pressure of water reduces partial pressure of gas"},
{cat:"unit3",q:"Preparing standard solutions",a:"Weigh solid, dissolve in volumetric flask, make to mark with distilled water",detail:"Use anhydrous compound or account for water of crystallisation"},
{cat:"unit3",q:"Choosing apparatus for accuracy",a:"Burette ±0.05 cm³ for titre; pipette for fixed volume; balance to 0.001 g for precise mass",detail:"Match apparatus precision to required accuracy"},
{cat:"unit3",q:"Evaluating experimental method",a:"Comment on validity (measures intended variable), reliability (repeatable), and improvements",detail:"Control variables, sample size, and equipment resolution strengthen evaluation"},
{cat:"unit3",q:"Filtration and drying organic product",a:"Filter under reduced pressure if needed; dry with anhydrous salt (MgSO₄) then distil or recrystallise",detail:"Test for dryness — clear organic layer"},
{cat:"unit3",q:"Melting point determination",a:"Pure compound: sharp mp close to literature value; impurity lowers and broadens mp range",detail:"Used to assess purity after recrystallisation"},
{cat:"unit3",q:"Planning a fair test",a:"Change one independent variable; control others; repeat and calculate mean; plot graph with line of best fit",detail:"Identify dependent variable and how it will be measured"},

// Unit 4 — Rates, Equilibria and Further Organic Chemistry
{cat:"unit4",q:"Rate equation",a:"Rate = k[A]^m[B]^n; orders m, n found experimentally (not from coefficients)",detail:"Overall order = m + n; units of k depend on overall order"},
{cat:"unit4",q:"Half-life of first-order reaction",a:"Constant t½; t½ = 0.693/k",detail:"Graph of [A] vs time — successive halves take equal time"},
{cat:"unit4",q:"Rate-determining step",a:"Slowest step controls rate; mechanism must match rate equation (species in RDS determine orders)",detail:"SN1: rate ∝ [halogenoalkane]; SN2: rate ∝ [halogenoalkane][nucleophile]"},
{cat:"unit4",q:"Arrhenius equation (graphical)",a:"ln k = –Ea/R × (1/T) + constant; gradient of ln k vs 1/T = –Ea/R",detail:"Ea in J mol⁻¹ when R = 8.31 J K⁻¹ mol⁻¹"},
{cat:"unit4",q:"Entropy (ΔSsystem)",a:"Measure of disorder; gases >> liquids > solids; ΔS positive when disorder increases",detail:"Calculate from standard entropy data: ΔS° = ΣS°(products) – ΣS°(reactants)"},
{cat:"unit4",q:"Total entropy and feasibility",a:"ΔStotal = ΔSsystem + ΔSsurroundings; ΔSsurroundings = –ΔH/T; feasible if ΔStotal > 0",detail:"At equilibrium ΔStotal = 0; link to ΔG = ΔH – TΔS"},
{cat:"unit4",q:"Born–Haber cycle terms",a:"Atomisation, ionisation, electron affinity, lattice energy combine with formation enthalpy in cycle",detail:"Lattice formation is exothermic (negative) when defined for ionic solid from gas ions"},
{cat:"unit4",q:"Lattice energy trends",a:"↑ ionic charge and ↓ ionic radius → ↑ lattice energy; experimental vs theoretical shows covalent character if differ",detail:"Born–Landé equation qualitative reasoning sufficient"},
{cat:"unit4",q:"Enthalpy of solution and hydration",a:"ΔsolH = ΔlattH + ΔhydH; hydration stabilises ions in water",detail:"Exothermic hydration can outweigh endothermic lattice breakdown"},
{cat:"unit4",q:"Kc expression",a:"For aA + bB ⇌ cC + dD: Kc = [C]^c[D]^d ÷ [A]^a[B]^b; solids and pure liquids omitted",detail:"Concentrations at equilibrium in mol dm⁻³; units depend on stoichiometry"},
{cat:"unit4",q:"Kp expression",a:"Kp uses partial pressures (Pa or kPa); only gaseous species included",detail:"Kp = Kc(RT)^Δn for ideal gases"},
{cat:"unit4",q:"Effect of temperature on K",a:"Temperature change shifts K; exothermic forward reaction: ↑T decreases K",detail:"Concentration and pressure do not change K — only position"},
{cat:"unit4",q:"Brønsted–Lowry acids and bases",a:"Acid proton donor; base proton acceptor; conjugate pairs differ by H⁺",detail:"pH = –log₁₀[H⁺]; [H⁺] = 10^(–pH)"},
{cat:"unit4",q:"Weak acid Ka and pKa",a:"Ka = [H⁺][A⁻]÷[HA]; pKa = –log Ka; larger Ka = stronger acid",detail:"For weak acid: [H⁺] ≈ √(Ka × [HA]) if α small"},
{cat:"unit4",q:"Kw and neutral pH",a:"Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ mol² dm⁻⁶ at 298 K; pH 7 neutral only at 25°C",detail:"Strong base: find [OH⁻] then [H⁺] = Kw/[OH⁻]"},
{cat:"unit4",q:"Buffer solutions",a:"Weak acid + salt of conjugate base (or weak base + salt); resist pH change on small addition of H⁺/OH⁻",detail:"Henderson–Hasselbalch: pH = pKa + log([A⁻]/[HA])"},
{cat:"unit4",q:"Titration curves and indicators",a:"Strong acid + strong base: pH 7 at equivalence; weak acid + strong base: pH > 7; half-equivalence → pH = pKa",detail:"Indicator pKin range should match steep vertical region"},
{cat:"unit4",q:"Chirality and optical activity",a:"Chiral centre: four different groups on C; enantiomers non-superimposable mirror images; racemic mixture not optically active",detail:"SN1 often gives racemate; SN2 inverts configuration"},
{cat:"unit4",q:"Carbonyl tests",a:"2,4-DNP: orange ppt (aldehyde/ketone); Tollens' silver mirror (aldehyde); Fehling's red ppt (aldehyde); iodoform CH₃CO– group → yellow ppt",detail:"LiAlH₄ or NaBH₄ reduce C=O to alcohol"},
{cat:"unit4",q:"Carboxylic acid reactions",a:"PCl₅ → acyl chloride; with alcohol → ester; LiAlH₄ → primary alcohol; with base → salt",detail:"Oxidation of 1° alcohol or nitrile hydrolysis gives acid"},
{cat:"unit4",q:"Acyl chloride reactions",a:"With H₂O, ROH, NH₃, RNH₂ — fast nucleophilic addition-elimination at room temperature",detail:"HCl fumes; more reactive than carboxylic acid"},
{cat:"unit4",q:"Ester hydrolysis",a:"Acid: reversible; alkali (NaOH): irreversible saponification → carboxylate + alcohol",detail:"Polyesters from diacid + diol condensation"},
{cat:"unit4",q:"¹³C NMR",a:"Number of peaks = number of unique carbon environments; chemical shift (δ ppm) indicates functional group type",detail:"No splitting in ¹³C NMR"},
{cat:"unit4",q:"¹H NMR — integration and splitting",a:"Peak area ∝ number of equivalent H; (n+1) rule: adjacent n equivalent H splits into n+1 peaks",detail:"TMS reference δ = 0; D₂O exchange removes O–H peak"},
{cat:"unit4",q:"Chromatography — HPLC and GC",a:"Rf on TLC; HPLC/GC: retention time identifies components; GC-MS combines separation and mass ID",detail:"More polar analytes often longer retention on polar columns"},

// Unit 5 — Transition Metals and Organic Nitrogen Chemistry
{cat:"unit5",q:"Standard electrode potential E°",a:"Emf of half-cell vs SHE at 298 K, 100 kPa, 1 mol dm⁻³; reduction written as reduction on RHS of cell diagram",detail:"More positive E° = stronger oxidising agent (easier to reduce)"},
{cat:"unit5",q:"E°cell calculation",a:"E°cell = E°(reduction) – E°(oxidation); E°cell > 0 → thermodynamically feasible cell reaction",detail:"Write overall equation from half-equations; check electrons balance"},
{cat:"unit5",q:"Limitations of E° predictions",a:"Thermodynamic feasibility ≠ fast reaction; non-standard conditions change electrode potentials",detail:"Kinetics may prevent observable reaction despite positive E°cell"},
{cat:"unit5",q:"Redox titration — MnO₄⁻/Fe²⁺",a:"Acidified KMnO₄ (purple) titrated into Fe²⁺; endpoint faint pink; 5Fe²⁺ + MnO₄⁻ + 8H⁺ → 5Fe³⁺ + Mn²⁺ + 4H₂O",detail:"H₂SO₄ provides H⁺; avoid HCl (Cl⁻ oxidised)"},
{cat:"unit5",q:"Iodine–thiosulfate titration",a:"I₂ + 2S₂O₃²⁻ → 2I⁻ + S₄O₆²⁻; starch indicator blue-black until I₂ consumed",detail:"Used after generating I₂ from oxidising agent e.g. Copper²⁺"},
{cat:"unit5",q:"Disproportionation and fuel cells",a:"Same element oxidised and reduced; H₂/O₂ fuel cell: H₂ → 2H⁺ + 2e⁻ (anode), O₂ + 4H⁺ + 4e⁻ → 2H₂O (acidic cathode)",detail:"Alkaline cell uses OH⁻ transport"},
{cat:"unit5",q:"Transition metal definition",a:"d-block element forming at least one stable ion with incomplete d subshell; variable oxidation states, coloured ions, catalysts",detail:"Zn²⁺ is d¹⁰ — not coloured; still often studied with d-block"},
{cat:"unit5",q:"Fe electronic configurations",a:"Fe atom: [Ar] 3d⁶ 4s²; Fe²⁺: [Ar] 3d⁶; Fe³⁺: [Ar] 3d⁵",detail:"4s electrons lost before 3d when forming 2+ ion"},
{cat:"unit5",q:"Complex ions and ligands",a:"Ligand donates lone pair (dative covalent bond); coordination number = number of coordinate bonds; shapes: octahedral (6), tetrahedral/square planar (4)",detail:"Examples: [Cu(H₂O)₆]²⁺, [Ni(NH₃)₆]²⁺"},
{cat:"unit5",q:"Colour in transition metal complexes",a:"Ligands split 3d orbitals; coloured ion absorbs complementary light; colourless if d⁰ or d¹⁰",detail:"Change of ligand → change in ΔE → colour change"},
{cat:"unit5",q:"Metal ions with NaOH(aq)",a:"Fe²⁺ green ppt → brown in air; Fe³⁺ brown; Cu²⁺ blue ppt; Co²⁺ blue ppt → pink in excess if noted",detail:"Many hydroxides insoluble; some dissolve in excess NaOH"},
{cat:"unit5",q:"Ligand exchange — copper complexes",a:"[Cu(H₂O)₆]²⁺ (pale blue) + 4NH₃ → deep blue [Cu(NH₃)₄(H₂O)₂]²⁺; excess Cl⁻ → yellow [CuCl₄]²⁻",detail:"Equilibrium shifted by concentration of ligand"},
{cat:"unit5",q:"Bidentate and chelate effect",a:"en (ethane-1,2-diamine) forms two bonds; EDTA⁴⁻ hexadentate; chelates more stable (entropy gain on displacement of more molecules)",detail:"Haemoglobin: Fe²⁺ with polydentate porphyrin; CO binds strongly — poisoning"},
{cat:"unit5",q:"Vanadium oxidation states",a:"+5 VO₂⁺ yellow, +4 VO²⁺ blue, +3 V³⁺ green, +2 V²⁺ violet; interconvert with Zn/H⁺ or oxidise with MnO₄⁻",detail:"Classic demonstration of variable oxidation state"},
{cat:"unit5",q:"Heterogeneous catalysis",a:"Adsorption → reaction on surface → desorption; e.g. V₂O₅ in Contact process; catalytic converters 2CO + 2NO → 2CO₂ + N₂",detail:"Poisoning blocks surface sites"},
{cat:"unit5",q:"Homogeneous catalysis",a:"Fe²⁺/Fe³⁺ cycle in S₂O₈²⁻ + I⁻; Mn²⁺ autocatalysis in MnO₄⁻ + C₂O₄²⁻",detail:"Catalyst in same phase as reactants"},
{cat:"unit5",q:"Benzene structure and stability",a:"Delocalised π system; enthalpy of hydrogenation less exothermic than Kekulé predicted; resistant to addition",detail:"X-ray: equal C–C bond lengths; IR lacks isolated C=C"},
{cat:"unit5",q:"EAS — bromination and nitration",a:"Br₂ + FeBr₃; HNO₃ + H₂SO₄ ~50°C → NO₂⁺ electrophile",detail:"FeBr₃ generates Br⁺; temperature control prevents dinitration"},
{cat:"unit5",q:"Friedel–Crafts reactions",a:"Alkylation: RCl + AlCl₃; acylation: RCOCl + AlCl₃ → acylbenzene (no rearrangement of acylium)",detail:"Cannot use on ring deactivated by –NO₂"},
{cat:"unit5",q:"Substituent directing effects",a:"Activating –OH, –NH₂: ortho/para directors; deactivating –NO₂: meta director",detail:"Steric hindrance favours para over ortho for bulky groups"},
{cat:"unit5",q:"Nitrobenzene → phenylamine",a:"Sn + conc. HCl, heat under reflux; then NaOH to liberate free amine",detail:"Six-electron reduction NO₂ → NH₂"},
{cat:"unit5",q:"Amine basicity",a:"Lone pair on N accepts H⁺; aliphatic amines more basic than NH₃; phenylamine weaker (lone pair delocalised into ring)",detail:"Forms ammonium salts with acids"},
{cat:"unit5",q:"Diazonium salt and azo dye",a:"PhNH₂ + NaNO₂ + HCl, <10°C → PhN₂⁺; couple with phenol/amine in alkaline solution → coloured azo –N=N–",detail:"Diazonium unstable above 10°C"},
{cat:"unit5",q:"Amino acids and zwitterions",a:"H₂N–CHR–COOH; zwitterion ⁺H₃N–CHR–COO⁻ at intermediate pH; isoelectric point where net charge zero",detail:"Peptide bond: –CONH– from condensation between amino acids"},
{cat:"unit5",q:"Polyamides — nylon and Kevlar",a:"Diamine + diacid chloride or diacid; condensation polymerisation; amide link same as peptide bond",detail:"Kevlar: rigid chains, strong H-bonding between chains"},

// Unit 6 — Practical Skills in Chemistry II
{cat:"unit6",q:"Core Practical 9a — iodine–propanone rate",a:"Titrate I₂ with sodium thiosulfate at timed intervals; rate from disappearance of I₂",detail:"Acid catalyst; control temperature"},
{cat:"unit6",q:"Core Practical 9b — iodine clock",a:"Mix solutions so blue-black starch–I₂ appears after fixed time; investigate effect of concentration/T on rate",detail:"Qualitative or semi-quantitative timing"},
{cat:"unit6",q:"Core Practical 10 — activation energy",a:"Measure rate at several temperatures; plot ln k vs 1/T; gradient = –Ea/R",detail:"Same method as Arrhenius graphical determination"},
{cat:"unit6",q:"Core Practical 11 — Ka of weak acid",a:"Measure pH of known concentration weak acid; Ka = [H⁺]² ÷ [HA] if degree dissociation small",detail:"Or pH at half-equivalence in titration with strong base"},
{cat:"unit6",q:"Core Practical 12 — electrochemical cells",a:"Measure cell emf with high-resistance voltmeter; cell diagram: single lines phases, double salt bridge, reduction on RHS",detail:"Standard conditions or state concentrations used"},
{cat:"unit6",q:"Core Practical 13a — KMnO₄/Fe²⁺ titration",a:"Acidify Fe²⁺ with H₂SO₄; titrate with KMnO₄ to first permanent pale pink",detail:"Self-indicating endpoint; practice filling burette safely"},
{cat:"unit6",q:"Core Practical 13b — iodine–thiosulfate",a:"Generate or add known I₂; titrate with Na₂S₂O₃ until starch endpoint goes colourless",detail:"Starch added near end point"},
{cat:"unit6",q:"Core Practical 14 — transition metal complex",a:"Prepare e.g. [Cu(NH₃)₄]²⁺ or similar; observe colour change on ligand addition",detail:"Record exact reagents and observations for marks"},
{cat:"unit6",q:"Core Practical 15 — multi-step organic synthesis",a:"Plan route; reflux/distil/recrystallise; test purity by melting point and spectroscopy",detail:"Document yields and purification steps"},
{cat:"unit6",q:"Interpreting ¹H NMR in unknowns",a:"Count environments, integration ratios, splitting patterns, δ values for –CH₃, –OH (exchangeable), aromatic H",detail:"Use data booklet chemical shift ranges"},
{cat:"unit6",q:"Interpreting ¹³C NMR and IR together",a:"¹³C: count carbon environments; IR: confirm C=O, O–H, N–H present or absent",detail:"Cross-check with molecular formula from mass spec"},
{cat:"unit6",q:"Mass spectrometry in analysis",a:"M⁺ or [M+H]⁺ for Mr; fragmentation (e.g. loss of 15 CH₃, 29 C₂H₅) suggests structure",detail:"High resolution distinguishes C₄H₈ vs C₃H₄O"},
{cat:"unit6",q:"Chromatography in unfamiliar context",a:"Compare Rf or retention time to standards; GC-MS gives mass spectrum of each peak",detail:"Impure sample shows multiple spots/peaks"},
{cat:"unit6",q:"Percentage uncertainty",a:"% uncertainty = (absolute uncertainty ÷ value) × 100%; combine for multiplied/divided quantities",detail:"Report final value to consistent significant figures"},
{cat:"unit6",q:"Systematic error in advanced practicals",a:"e.g. incomplete reaction, heat loss, indicator choice, junction potential in cells",detail:"Suggest specific improvement not just 'repeat'"},
{cat:"unit6",q:"Validity vs reliability",a:"Valid: measures what it claims; reliable: repeatable results; fair test controls variables",detail:"One anomalous result — identify and optionally exclude with justification"},
{cat:"unit6",q:"pH meter calibration",a:"Calibrate with buffer solutions pH 4 and 7 (or 10) before weak acid Ka experiment",detail:"Rinse electrode with distilled water between solutions"},
{cat:"unit6",q:"Cell emf and concentration cells",a:"Non-standard concentrations change electrode potentials (Nernst); emf may differ from E°cell",detail:"State concentrations when not standard"},
{cat:"unit6",q:"Purifying organic product",a:"Recrystallise from minimum hot solvent; filter cold; dry and determine melting point",detail:"Impurity broadens and lowers mp"},
{cat:"unit6",q:"Writing a practical conclusion",a:"Link results to hypothesis; compare to literature; state main uncertainty and its effect on conclusion",detail:"Use data with units; quote calculated values"},
{cat:"unit6",q:"Rate data processing",a:"Initial rates method or half-life from concentration–time graph; units of k from overall order",detail:"Log graphs linearise exponential relationships"},
{cat:"unit6",q:"Safety in Unit 4–5 practicals",a:"KMnO₄ oxidiser, organic solvents flammable, conc. acids corrosive — risk assessment before work",detail:"Small-scale reactions where possible"}
];
